name: 'name'

environment:
  sdk: ^3.2.5

dependencies:
  # flavor mock
  args: ^2.4.2
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  # end flavor mock

fonts: 
  - family: 'inter'
    fonts: 
      - asset: 'assets/common/fonts/inter/inter-Regular.ttf'
        weight: 300
      - asset: 'assets/common/fonts/inter/inter-Regular.ttf'
        weight: 400
      - asset: 'assets/common/fonts/inter/inter-Regular.ttf'
        weight: 500
