name: flavors_yaml_merger
description: A package to help building flavored apps without the need to manually remove other flavor content from yaml file.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
